services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/rainy-day
    command: sleep infinity  # devcontainers override this
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rainy-day
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
